RegisterNetEvent("Client:RAW",function(d)
    print("raw data",d)
end)
RegisterNetEvent("Client:HALF",function(d)
    print("compress data",LibCompress:Decompress(d))
end)

RegisterCommand("clearrrr",function()
    TriggerServerEvent("-----------------")
end,false)
RegisterCommand("GETRAW",function()
    TriggerServerEvent("Server:RAW")
end,false)
RegisterCommand("GETHALF",function()
    TriggerServerEvent("Server:HALF")
end,false)